resources:
- name: hello-world
  type: git
  source:
    uri: https://github.com/lalfaro2/hello-world
    branch: main

jobs:
  - name: run-script
    plan:
      - get: hello-world
        trigger: true
      - task: run-script
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
              tag: "latest"
          inputs:
            - name: hello-world
          run:
            path: /bin/bash
            args:
              - "-c"
              - |
                cd hello-world
                bash ./lmao.sh
